# Generated by Django 4.2.7 on 2023-11-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba2db', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='comment',
            new_name='description',
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='anonymous', max_length=1000),
        ),
        migrations.AddField(
            model_name='query',
            name='title',
            field=models.CharField(default='No title', max_length=1000),
        ),
        migrations.AddField(
            model_name='query',
            name='username',
            field=models.CharField(default='anonymous', max_length=1000),
        ),
    ]
